<?php


/**
 * Implementation of hook_ctools_plugin_directory().
 */
function quicktabs_content_ctools_plugin_directory($module, $plugin) {
  if (($module == 'ctools' || $module == 'panels') && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implementation of hook_ctools_block_info().
 * 
 * @param type $module
 * @param type $delta
 * @param type $info
 * 
 * cTools only calls this hook for modules that implement hook_block(),
 * so we have to use Quicktabs' namespace.
 */ 
function quicktabs_ctools_block_info($module, $delta, &$info) {
  // Remove quicktabs from the "Miscellaneous" blocks.
  if ($module == 'quicktabs') {
    $info = NULL;
  }
}




